/* ============================================================
   ITEMS.JS — This is the ONLY file you need to edit!
   ============================================================

   HOW TO ADD AN ITEM:
   1. Copy one of the item blocks below (from "{" to "},")
   2. Paste it into the right category section
   3. Fill in the fields:
        category  : must match one of the category ids below
        nameEn    : product name in English
        nameKo    : product name in Korean
        noteEn    : your one-line comment in English (why you love it)
        noteKo    : same comment in Korean
        reviewEn  : (optional) your longer personal review, a few sentences —
                    shows as an italic quote under the note
        reviewKo  : (optional) same review in Korean
        amazonUrl : your Amazon AFFILIATE link (from SiteStripe — see README)
        otherUrl  : (optional) link for items not sold on Amazon
        verdict   : "absolute"  shows the 무조건! (absolute must!) label
                    "essential" shows the 사라사! (must!) label
                    anything else (or leaving it out) shows 좋을지도? (maybe?)
        travel    : true = shows a small "✈ travel" tag (for travel-optimized gear)
   4. Save the file. Done — the page updates automatically.

   To REMOVE an item, delete its whole block (from "{" to "},").
   ============================================================ */

// ---------- SITE SETTINGS ----------
const SITE_CONFIG = {
  // Your Amazon Associates tag, e.g. "juliagives-20".
  // Once you fill this in, it is automatically added to every
  // Amazon link on the page (links pasted from SiteStripe
  // already contain it, so either way works).
  amazonTag: "",

  kickerEn: "A twin family's honest list",
  kickerKo: "쌍둥이 가족의 솔직한 리스트",

  titleEn: "The things that actually worked",
  titleKo: "정말 도움이 된 것들만 모았습니다",

  subtitleEn: "Our twins arrived in spring 2025. Every item below was bought with our own money and tested through plenty of trial and error. This is the list we wish someone had handed us.",
  subtitleKo: "2025년 봄, 쌍둥이가 태어났습니다. 아래 물건들은 전부 저희 돈으로 직접 사서 많은 시행착오를 거쳐 검증한 것들이에요. 누군가 우리에게 먼저 건네줬더라면 좋았을 리스트입니다.",

  charityEn: "When you buy through these links, Amazon pays us a small commission — your price stays the same. 100% of our net proceeds from these links are donated to March of Dimes, which supports NICU families and research for healthy moms and babies.",
  charityKo: "이 링크로 구매하시면 아마존이 저희에게 소정의 커미션을 지급합니다. 이 링크를 통한 순수익 전액은 신생아 집중치료실(NICU) 가족과 건강한 출산을 위한 연구를 지원하는 March of Dimes에 기부됩니다.",

  disclosureEn: "As an Amazon Associate I earn from qualifying purchases. 100% of our net proceeds from these links are donated to March of Dimes.",
  disclosureKo: "본 페이지는 아마존 어소시에이트 활동의 일환으로, 적격 구매 시 아마존으로부터 커미션을 받습니다. 이 링크를 통한 순수익 전액은 March of Dimes에 기부됩니다.",
};

// ---------- CATEGORIES ----------
// (id is used internally — don't change it once items use it)
const CATEGORIES = [
  { id: "feeding",   emoji: "🍼", en: "Feeding",         ko: "수유 · 이유식" },
  { id: "sleeping",  emoji: "🌙", en: "Sleep",           ko: "수면" },
  { id: "diapering", emoji: "🧷", en: "Diapering",       ko: "기저귀" },
  { id: "gear",      emoji: "🚗", en: "Gear & On-the-Go", ko: "외출 · 이동" },
  { id: "health",    emoji: "💊", en: "Health",          ko: "건강" },
  { id: "safety",    emoji: "🛡️", en: "Safety",          ko: "안전" },
  { id: "bathing",   emoji: "🛁", en: "Bath",            ko: "목욕" },
  { id: "playing",   emoji: "🧸", en: "Play",            ko: "놀이" },
  { id: "italy",     emoji: "🇮🇹", en: "Found in Italy",  ko: "이탈리아에서 산 것들" },
  { id: "extras",    emoji: "✨", en: "Little Extras",   ko: "소소한 아이템" },
];

// ---------- ITEMS ----------
const ITEMS = [

  // ================= FEEDING · 수유/이유식 =================
  {
    category: "feeding",
    nameEn: "Stokke Tripp Trapp High Chair + Newborn Set",
    nameKo: "스토케 트립트랩 하이체어 + 뉴본 세트",
    noteEn: "One chair, zero repurchases — seat height and depth adjust as they grow, so you're not buying a new highchair at every stage. Norwegian design that treats a highchair as furniture, not a plastic appliance you hide when guests come over.",
    noteKo: "의자 하나로 재구매가 필요 없어요 — 좌석 높이와 깊이가 성장에 맞춰 조절돼요. 손님 올 때 숨기고 싶은 플라스틱 제품이 아니라 진짜 가구처럼 디자인한 노르웨이 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B0BWSM3765",
    image: "https://m.media-amazon.com/images/I/51dBY8Ee4mL._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "feeding",
    nameEn: "Baby Brezza Bottle Washer Pro",
    nameKo: "베이비 브레자 보틀 워셔 프로",
    noteEn: "Twenty minutes of hand-washing, sterilizing, and air-drying collapsed into one countertop machine — with twins, that's roughly two hours back every week. The design bet: charge a premium once so parents never think about bottle-washing as a task again.",
    noteKo: "손 설거지, 소독, 건조에 들던 시간이 카운터 위 기계 하나로 끝나요 — 쌍둥이 육아에서는 매주 약 두 시간을 돌려받는 셈이에요. 처음에 프리미엄 가격을 매기는 대신, '젖병 설거지'라는 일 자체를 지워버리겠다는 제품 전략이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0CKRWC8ZN",
    image: "https://m.media-amazon.com/images/I/71Oo8N-tU7L._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "feeding",
    nameEn: "Baby Brezza Formula Pro Advanced (Formula Dispenser)",
    nameKo: "베이비 브레자 포뮬러 프로 어드밴스드 (자동 분유 제조기)",
    noteEn: "Push a button, get a bottle at the exact temperature and ratio, every time — the appeal isn't speed so much as removing decision fatigue at 3am. Brezza's whole line bets parents will pay to never measure powder or test temperature on their wrist again.",
    noteKo: "버튼 하나로 매번 정확한 온도와 비율의 분유가 나와요 — 핵심은 속도가 아니라 새벽 3시의 판단 피로를 없애주는 거예요. 다시는 가루를 계량하거나 손목에 온도를 테스트하지 않아도 된다는 데 돈을 지불하는 브랜드 전략이에요.",
    amazonUrl: "https://www.amazon.com/dp/B07MYW28QR",
    image: "https://m.media-amazon.com/images/I/71ysfmyOu+L._AC_SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "feeding",
    nameEn: "Baby Brezza Superfast Portable Bottle Warmer",
    nameKo: "베이비 브레자 휴대용 보틀 워머",
    noteEn: "No outlet, no waiting — the cordless spinoff of the countertop warmer, aimed squarely at the car and the middle-of-the-night feed. A smart brand-extension move: same trust, smaller form factor, different use case.",
    noteKo: "콘센트도, 기다림도 필요 없어요 — 카운터형 워머의 무선 파생 제품으로, 차 안과 새벽 수유를 정확히 겨냥했어요. 같은 브랜드 신뢰도를 더 작은 폼팩터로 확장한 영리한 라인업 전략이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0DPL81FJM",
    image: "https://m.media-amazon.com/images/I/61OEHjWW8XL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "feeding",
    nameEn: "Dr. Brown's Formula Mixing Pitcher",
    nameKo: "닥터브라운 분유 믹싱 피처",
    noteEn: "Mix a full day's formula in one clump-free batch instead of shaking bottles six times a day — for twins, that's a five-minute morning task instead of an all-day chore. A quiet piece of category-defining design: people trust the vented-bottle brand's other products without asking why.",
    noteKo: "하루치 분유를 한 번에 덩어리 없이 섞어두면, 하루 여섯 번씩 개별 병을 흔드는 대신 아침 5분 작업으로 끝나요 — 쌍둥이라면 하루 종일 걸리던 일이 이렇게 줄어들어요. 벤트 젖병으로 카테고리를 정의한 브랜드답게, 다른 제품도 이유를 따지지 않고 신뢰하게 되는 조용한 디자인 우위예요.",
    amazonUrl: "https://www.amazon.com/dp/B01ABOYJNI",
    image: "https://m.media-amazon.com/images/I/71G1vDmFAoL._AC_SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "feeding",
    nameEn: "Inglesina Fast Table Chair",
    nameKo: "잉글레시나 패스트 테이블 체어",
    noteEn: "Clamps onto any table in under a minute and folds flat into a tote bag — the whole value proposition is portability without looking like camping gear. An Italian brand doing what Italian design usually does: make the functional object look intentional too.",
    noteKo: "1분 안에 테이블에 고정되고 가방에 납작하게 들어가요 — 캠핑 장비처럼 안 보이면서 휴대성을 확보한 게 이 제품의 전부예요. 기능적인 물건도 의도된 디자인처럼 보이게 만드는, 이탈리아 디자인다운 접근이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00IOGIM9S",
    image: "https://m.media-amazon.com/images/I/71JwQyi6KPL._SL1500_.jpg",
    verdict: "essential",
    travel: true,
  },
  {
    category: "feeding",
    nameEn: "BabyBjörn Baby Bib (2 Pack)",
    nameKo: "베이비뵨 턱받이 (2개 세트)",
    noteEn: "The silicone pocket actually catches falling food instead of just wiping around the mouth — you feel the difference the first time you don't sweep the floor after lunch. Swedish restraint: one simple shape, no cartoon characters, still the bib everyone recognizes.",
    noteKo: "실리콘 포켓이 흘리는 음식을 실제로 받아줘요 — 식사 후 바닥을 안 쓸어도 된다는 걸 처음 겪으면 차이를 바로 느껴요. 캐릭터 하나 없는 단순한 형태인데도 누구나 알아보는, 스웨덴다운 절제된 디자인이에요.",
    amazonUrl: "https://www.amazon.com/dp/B07NF5SVMZ",
    image: "https://m.media-amazon.com/images/I/61gdw3BRDBL._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Dr. Brown's Options+ Anti-Colic Bottles (4 oz, 4-Pack)",
    nameKo: "닥터브라운 옵션스+ 안티콜릭 젖병 (4oz, 4개)",
    noteEn: "The internal vent system genuinely cuts down on air intake — less gas, less 2am crying, which is the entire pitch and it delivers. More parts to clean than competing bottles, a deliberate trade-off: more parts, less colic.",
    noteKo: "내부 벤트 구조가 실제로 공기 유입을 줄여줘요 — 가스와 새벽 울음이 줄어든다는 게 전부인데, 실제로 그렇게 돼요. 세척은 다른 젖병보다 손이 더 가는데, '부품은 늘고 배앓이는 준다'는 의도된 트레이드오프예요.",
    amazonUrl: "https://www.amazon.com/dp/B01845QGKK",
    image: "https://m.media-amazon.com/images/I/714N9O9walL._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Hegen PCTO Feeding Bottles (240 ml/8 oz, 2-Pack)",
    nameKo: "헤겐 PCTO 젖병 (240ml, 2개)",
    noteEn: "One container serves as bottle, breast-milk storage, and toddler dish — you buy fewer things and wash fewer things, which is the real design win here, not the aesthetics. A Singaporean brand doing smart line extension: same base unit, different lid, different life stage.",
    noteKo: "용기 하나가 젖병, 유축 보관, 이유식 그릇 역할을 다 해요 — 사야 할 것도, 씻어야 할 것도 줄어드는 게 예쁜 디자인보다 진짜 중요한 부분이에요. 같은 본체에 뚜껑만 바꿔 다른 인생 단계에 대응하는, 싱가포르 브랜드의 영리한 라인 확장이에요.",
    amazonUrl: "",
    otherUrl: "https://www.hegen.us/products/hegen-8oz-240ml-ppsu-feeding-bottle-in-2-pack",
  },
  {
    category: "feeding",
    nameEn: "Dr. Brown's Folding Bottle Drying Rack",
    nameKo: "닥터브라운 접이식 젖병 건조대",
    noteEn: "Holds a full day's bottles upright to air-dry, then folds flat to disappear into a cabinet — solves the actual problem, which is counter space, not drying. Brand-extension logic: once you trust the vented bottle, you trust the accessory that stores it.",
    noteKo: "하루치 젖병을 세워서 건조하고, 안 쓸 땐 납작하게 접혀 수납장에 들어가요 — 진짜 문제는 건조가 아니라 조리대 공간이었다는 걸 해결해줘요. 벤트 젖병을 신뢰하면 그 젖병을 보관하는 제품도 믿게 되는, 같은 브랜드 확장 논리예요.",
    amazonUrl: "https://www.amazon.com/dp/B00HNVWGNS",
    image: "https://m.media-amazon.com/images/I/712JL9weJmL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Dapple Baby Bottle & Dish Soap (Fragrance-Free, 16.9 fl oz)",
    nameKo: "대플 젖병 세정제 (무향, 16.9 fl oz)",
    noteEn: "Cuts through dried milk film that regular dish soap just smears around — you notice bottles actually smell clean, not just soap-covered. A single-purpose product in a world of all-purpose soaps, which is exactly why it works better at the one job.",
    noteKo: "일반 주방세제로는 잘 안 지워지는 말라붙은 분유 막을 확실히 제거해줘요 — 병에서 비누 냄새가 아니라 진짜 깨끗한 냄새가 나요. 다용도 세제가 넘치는 시장에서 한 가지 용도에만 집중해서, 오히려 그 한 가지를 더 잘해요.",
    amazonUrl: "https://www.amazon.com/dp/B005UNYR38",
    image: "https://m.media-amazon.com/images/I/61wQ5+YfUrL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Munchkin Bristle Bottle Brush",
    nameKo: "먼치킨 브리슬 젖병솔",
    noteEn: "The bristle head reaches into narrow-neck bottles and pump parts without your hand doing the twisting — small thing, saves wrist strain across dozens of washes a day. Munchkin's whole catalog is this: unglamorous problems, solved cheaply and well.",
    noteKo: "브리슬 헤드가 좁은 입구의 젖병과 유축기 부품 안까지 손 없이 닿아요 — 사소해 보여도 하루 수십 번 설거지하는 손목엔 큰 차이예요. 먼치킨 제품군 전체가 이런 식이에요 — 화려하진 않은 문제를 저렴하고 잘 해결해요.",
    amazonUrl: "https://www.amazon.com/dp/B0CQKGR569",
    image: "https://m.media-amazon.com/images/I/61d98gnhKhL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "NIVAVA Nursing Pillow",
    nameKo: "니바바 수유쿠션",
    noteEn: "Firm foam that doesn't collapse under weight the way cheaper pillows do, so your arm actually gets the support it's supposed to — softer isn't always better here. A generic-feeling brand name, but the core engineering (density, shape retention) is where it counts.",
    noteKo: "저가 제품처럼 무게에 눌려 꺼지지 않는 단단한 폼 소재라 팔이 실제로 지지를 받아요 — 이 경우엔 푹신함이 항상 정답은 아니에요. 브랜드명은 낯설지만, 정말 중요한 밀도와 모양 유지력은 확실해요.",
    amazonUrl: "https://www.amazon.com/dp/B0C9M7BHBN",
    image: "https://m.media-amazon.com/images/I/61mmtruN1EL._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "MOTHER-K Disposable Bottle Liners (100pcs)",
    nameKo: "마더케이 일회용 젖병 비닐팩 (100매)",
    noteEn: "Disposable liners mean zero bottle-washing on the road — a small Korean product category solving a problem most Western brands ignore, since their parents wash bottles at home, not on a five-hour flight. Once you've used them on a trip, you resent every airport bathroom sink.",
    noteKo: "일회용 라이너 덕분에 여행 중 젖병 설거지가 아예 사라져요 — 서구권 브랜드들이 잘 신경 쓰지 않는, 한국 육아 시장이 먼저 알아챈 작은 카테고리예요. 한 번 여행에서 써보면 공항 화장실 세면대가 원망스러워져요.",
    amazonUrl: "https://www.amazon.com/dp/B0CHF4SS9N",
    image: "https://m.media-amazon.com/images/I/51UCB+K7hzL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "feeding",
    nameEn: "Amara Organic Baby Food (Stage 2)",
    nameKo: "아마라 유기농 이유식 (2단계)",
    noteEn: "Shelf-stable and mixes fresh with whatever liquid you have on hand — the real convenience is not refrigeration, it's not needing to plan ahead. Positioned between homemade purée and pouch food without fully committing to either.",
    noteKo: "실온 보관이 가능하고 손에 있는 아무 액체와 바로 섞어 쓸 수 있어요 — 진짜 편리함은 냉장 보관이 필요 없다는 것보다, 미리 계획하지 않아도 된다는 점이에요. 홈메이드 이유식과 파우치 이유식 사이 어중간한 자리를 노린 포지셔닝이에요.",
    amazonUrl: "https://www.amazon.com/dp/B07K2SHLYG",
    image: "https://m.media-amazon.com/images/I/81PaonbNXwL._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "NumNum GOOtensils Pre-Spoons (3-Pack)",
    nameKo: "넘넘 구텐실 이유식 스푼 (3개)",
    noteEn: "No scooping required — babies dip and lick, which sounds like a gimmick until you realize it's teaching self-feeding motor skills a spoon can't. A single clever insight stretched into an entire product line.",
    noteKo: "떠먹일 필요가 없어요 — 아기가 찍어서 빨아먹는 방식인데, 처음엔 신기해 보이지만 사실 숟가락으로는 못 가르치는 자기주도 식사 근육을 훈련시켜줘요. 하나의 영리한 통찰을 제품 라인 전체로 확장한 사례예요.",
    amazonUrl: "https://www.amazon.com/dp/B0CCW7278L",
    image: "https://m.media-amazon.com/images/I/51ofKU2Dc4L._AC_SL1080_.jpg",
  },
  {
    category: "feeding",
    nameEn: "WeeSprout Glass Baby Food Jars (12-Pack)",
    nameKo: "위스프라우트 유리 이유식 용기 (12개)",
    noteEn: "Goes from freezer to microwave without cracking, which sounds basic until you've had a cheaper jar shatter on you. An undifferentiated glass-jar category, but the one detail — thermal shock resistance — is the one that actually matters.",
    noteKo: "냉동실에서 전자레인지로 바로 가도 깨지지 않아요 — 당연해 보이지만, 저가 유리병이 깨지는 걸 한 번이라도 겪어보면 그렇지 않다는 걸 알게 돼요. 특별할 것 없는 유리용기 카테고리인데, 열충격 저항이라는 딱 한 가지 디테일이 진짜 중요해요.",
    amazonUrl: "https://www.amazon.com/dp/B0F32PMPV9",
    image: "https://m.media-amazon.com/images/I/71cGgm0J6dL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Firgi Silicone Rice Cooker Divider",
    nameKo: "실리콘 밥솥 칸막이 (이유식용)",
    noteEn: "Turns one rice cooker into three separate simmering compartments — batch-cook three purées at once instead of dirtying three pots. A niche accessory that only makes sense once you're deep into baby-food-batching mode.",
    noteKo: "밥솥 하나를 세 칸으로 나눠줘요 — 냄비 세 개를 어지르는 대신 이유식 세 가지를 한 번에 만들 수 있어요. 이유식 배치 조리에 본격적으로 들어간 부모에게만 의미가 생기는 니치 액세서리예요.",
    amazonUrl: "https://www.amazon.com/dp/B0DQ525DNP",
    image: "https://m.media-amazon.com/images/I/61P2kRYFNiL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Lallisa Silicone Fruit Feeder Spoons",
    nameKo: "실리콘 과일 스크래퍼 스푼",
    noteEn: "Scrapes soft fruit directly into a purée without a blender or extra dish — good for the one banana you need mashed at 7am, not a whole batch. A tiny, single-purpose tool that earns its drawer space.",
    noteKo: "믹서기나 여분의 그릇 없이 부드러운 과일을 바로 긁어서 이유식으로 만들어요 — 배치 조리가 아니라 아침에 바나나 하나 으깰 때 딱 맞아요. 서랍 한 칸을 차지할 자격이 있는, 작고 확실한 용도의 도구예요.",
    amazonUrl: "https://www.amazon.com/dp/B0BZBVLJM3",
    image: "https://m.media-amazon.com/images/I/61Vb-I6iCOL._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Thyseed Weighted Straw Cup",
    nameKo: "타이시드 무게추 빨대컵",
    noteEn: "The weighted straw stays submerged no matter how the cup tilts, so toddlers get liquid out at any angle without the classic no-spill-cup air-suck struggle. A mechanical fix to a mechanical problem, no gimmicks required.",
    noteKo: "무게추 빨대가 컵을 어떻게 기울여도 항상 액체 속에 잠겨 있어서, 흔한 노스필컵의 '빨아도 안 나오는' 문제가 없어요. 기계적인 문제를 기계적으로 해결한, 군더더기 없는 디자인이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0CB671LGX",
    image: "https://m.media-amazon.com/images/I/61hVchOX40L._SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Nuby Easy Go Portable Booster Seat",
    nameKo: "누비 이지고 휴대용 부스터 시트",
    noteEn: "Straps onto any dining chair in seconds — the entire product exists so you don't have to ask grandma to buy a highchair she'll use twice a year. Low-tech, and better for it.",
    noteKo: "어떤 식탁 의자에도 몇 초 만에 고정돼요 — 일 년에 두 번 쓸 하이체어를 조부모님께 사달라고 부탁할 필요가 없어지는 게 이 제품의 존재 이유예요. 기술적으로 단순한데, 그게 오히려 장점이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0FWT7LM1Q",
    image: "https://m.media-amazon.com/images/I/8194HrlaNiL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "feeding",
    nameEn: "Miss Mouth's Messy Eater Stain Treater",
    nameKo: "미스 마우스 이유식 얼룩 제거 스프레이",
    noteEn: "Actually lifts set-in baby-food stains days later, not just fresh ones — the test that matters, since laundry rarely happens same-day. A category of one: nobody else specifically targets 'toddler mess that already dried.'",
    noteKo: "묻은 지 며칠 지난 얼룩까지 지워줘요, 갓 생긴 얼룩만이 아니라 — 세탁이 그날 바로 이뤄지는 경우가 드무니 이게 진짜 중요한 테스트예요. '이미 말라붙은 아기 얼룩'이라는, 사실상 경쟁자가 없는 카테고리예요.",
    amazonUrl: "https://www.amazon.com/dp/B0BVXQQNBB",
    image: "https://m.media-amazon.com/images/I/61mv01U0ZDL._AC_SL1500_.jpg",
  },
  {
    category: "feeding",
    nameEn: "Richell Straw Training Mug",
    nameKo: "리첼 빨대 연습 컵 (스트로 머그)",
    noteEn: "The internal air valve keeps it from leaking even lying on its side in a diaper bag, which is where cups actually spend most of their life. A Japanese engineering answer to a problem most Western brands just accept as normal.",
    noteKo: "내부 공기 밸브 덕분에 기저귀 가방 안에 눕혀놔도 안 새요 — 사실 컵이 하루 대부분을 보내는 자세가 바로 그거예요. 대부분의 서구 브랜드가 그냥 감수하는 문제를, 일본식 엔지니어링으로 풀어낸 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B08BCT3LKC",
    image: "https://m.media-amazon.com/images/I/61s8oCZnRsL._SL1500_.jpg",
  },

  // ================= SLEEP · 수면 =================
  {
    category: "sleeping",
    nameEn: "babyletto Yuzu 8-in-1 Convertible Crib",
    nameKo: "베이비레토 유주 8-in-1 컨버터블 아기침대",
    noteEn: "Converts bassinet → crib → toddler bed → daybed, so the same piece of furniture ages with the kid instead of becoming landfill by age two. The conversion kits cost extra later, which is the quiet catch in every 'buy once' crib pitch.",
    noteKo: "배시넷 → 크립 → 유아 침대 → 데이베드로 변신해서, 같은 가구가 아이와 함께 나이 들어요 — 두 살에 버려지는 대신에요. 나중에 전환 키트를 따로 사야 하는 게, '한 번만 사면 끝'이라는 크립 마케팅의 조용한 함정이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0BTPXVHBF",
    image: "https://m.media-amazon.com/images/I/71JoIVvVExL._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "sleeping",
    nameEn: "Newton Baby Breathable Crib Mattress",
    nameKo: "뉴턴 베이비 통기성 크립 매트리스",
    noteEn: "The whole mattress is washable and breathable enough to put your hand through it — reassuring at 2am when you're checking on a sleeping baby for the tenth time. The pitch is safety, but the real daily win is machine-washing the thing after a blowout.",
    noteKo: "매트리스 전체가 세탁 가능하고, 통기성이 좋아서 손을 대면 숨이 느껴질 정도예요 — 새벽에 열 번째로 아기를 확인할 때 안심이 돼요. 안전을 내세우지만, 실생활에서 진짜 좋은 건 대참사가 났을 때 통째로 세탁기에 돌릴 수 있다는 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B00WR958TA",
    image: "https://m.media-amazon.com/images/I/71VeejrijDL._AC_SL1500_.jpg",
  },
  {
    category: "sleeping",
    nameEn: "Newton Organic Cotton Crib Sheets (2 Pack)",
    nameKo: "뉴턴 오가닉 코튼 크립 시트 (2장)",
    noteEn: "Fitted specifically to the Newton mattress's unusual shape — a small lock-in, but the breathable weave is genuinely nicer than standard jersey. Buying the matched sheet is the tax you pay for buying the matched mattress.",
    noteKo: "뉴턴 매트리스의 독특한 형태에 딱 맞게 재단됐어요 — 약간의 락인 효과지만, 통기성 원단은 일반 저지 시트보다 확실히 좋아요. 세트 매트리스를 산 대가로 세트 시트도 사게 되는 구조예요.",
    amazonUrl: "https://www.amazon.com/dp/B09BBJ6SXN",
    image: "https://m.media-amazon.com/images/I/11xIhVvAlBL.jpg",
  },
  {
    category: "sleeping",
    nameEn: "Woolino 4 Season Ultimate Baby Sleep Bag",
    nameKo: "울리노 사계절 슬립백 (수면조끼)",
    noteEn: "Merino wool regulates temperature better than any fleece alternative, so you stop guessing what to layer underneath — one bag, every season, actual peace of mind. The price looks steep until you calculate how many seasonal bags you'd otherwise buy.",
    noteKo: "메리노 울이 어떤 플리스보다 체온 조절을 잘해줘서, 안에 뭘 입혀야 할지 더 이상 고민하지 않아도 돼요 — 하나로 사계절, 진짜 마음이 편해져요. 가격표만 보면 비싸 보이지만, 계절별로 따로 샀을 슬립백 개수를 계산해보면 답이 나와요.",
    amazonUrl: "https://www.amazon.com/dp/B07FNB81PH",
    image: "https://m.media-amazon.com/images/I/81xeSHSX75L._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "sleeping",
    nameEn: "Hatch Rest 2nd Gen + Rest Go Sound Machine Bundle",
    nameKo: "해치 레스트 사운드 머신 + 휴대용 레스트 고 세트",
    noteEn: "Phone-controlled sound and light means you're not tiptoeing across a dark room to adjust a dial — small thing, changes nightly life. The portable Rest Go extends the same interface to hotel rooms, which is where sleep routines usually fall apart.",
    noteKo: "휴대폰으로 소리와 조명을 조절하니, 어두운 방을 까치발로 가로질러 다이얼을 돌릴 필요가 없어요 — 사소하지만 매일 밤이 달라져요. 휴대용 레스트 고가 같은 인터페이스를 호텔 방까지 확장해줘서, 수면 루틴이 제일 무너지기 쉬운 곳을 커버해요.",
    amazonUrl: "https://www.amazon.com/dp/B0DCMJQYZS",
    image: "https://m.media-amazon.com/images/I/41QwAS8WxPL._AC_SL1080_.jpg",
    verdict: "essential",
    travel: true,
  },
  {
    category: "sleeping",
    nameEn: "Nanit Pro Baby Monitor",
    nameKo: "나닛 프로 베이비 모니터",
    noteEn: "The overhead angle (versus a side-mounted camera) actually shows breathing motion, not just a blurry silhouette — the detail that separates a real monitor from a webcam with a baby filter. You're paying for the analytics layer as much as the camera.",
    noteKo: "옆이 아니라 위에서 내려다보는 각도라 흐릿한 실루엣이 아니라 호흡 움직임이 실제로 보여요 — 이게 진짜 모니터와 아기용 필터 씌운 웹캠의 차이예요. 카메라 자체보다 분석 기능에 돈을 내는 셈이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0BG3L9P73",
    image: "https://m.media-amazon.com/images/I/716Q5OzuTiL._SL1500_.jpg",
  },
  {
    category: "sleeping",
    nameEn: "Owlet Dream Sock Smart Baby Monitor",
    nameKo: "아울렛 드림 삭스 스마트 모니터",
    noteEn: "Tracks oxygen and heart rate on a sock, not a bulky monitor strapped to the chest — for a NICU-graduate family especially, the data is less about function and more about not lying awake wondering. The alert features are the actual product; the sock is just the sensor.",
    noteKo: "가슴에 두르는 큰 모니터가 아니라 양말 형태로 산소포화도와 심박수를 측정해요 — 니큐 졸업 가족에게는 기능보다 '누워서 불안해하지 않아도 된다'는 게 진짜 가치예요. 사실상 진짜 제품은 알림 기능이고, 양말은 센서일 뿐이에요.",
    amazonUrl: "https://www.amazon.com/dp/B09YVSYGDW",
    image: "https://m.media-amazon.com/images/I/61p5jOP5fKL._SL1500_.jpg",
  },
  {
    category: "sleeping",
    nameEn: "Tapo 2K Pan/Tilt Camera (2-Pack)",
    nameKo: "타포 2K 팬틸트 카메라 (2대)",
    noteEn: "Pan and tilt from your phone at a fraction of the premium-monitor price — no breathing analytics, just a genuinely competent camera. The value play: skip the data science, keep the one feature that actually matters at 3am — seeing your kid.",
    noteKo: "프리미엄 모니터 가격의 일부만으로 휴대폰에서 팬·틸트 조절이 돼요 — 호흡 분석은 없지만, 카메라 성능 자체는 충분해요. 데이터 분석은 빼고, 새벽 3시에 진짜 필요한 딱 한 가지(아이가 보이는 것)만 남긴 가성비 전략이에요.",
    amazonUrl: "https://www.amazon.com/dp/B09Y8C185M",
    image: "https://m.media-amazon.com/images/I/51c2KSMYLRL._AC_SL1500_.jpg",
  },

  // ================= DIAPERING · 기저귀 =================
  {
    category: "diapering",
    nameEn: "Coterie Ultra Soft Diapers",
    nameKo: "코테리 울트라 소프트 기저귀",
    noteEn: "Thinner than legacy diapers but somehow more absorbent — the material science is the entire brand story, and it holds up overnight. DTC pricing without a subscription commitment was the real innovation; Amazon and Whole Foods distribution came later once trust was already built.",
    noteKo: "기존 기저귀보다 얇은데 흡수력은 오히려 더 좋아요 — 소재 기술이 브랜드 스토리의 전부고, 실제로 밤새 버텨줘요. 구독 강제 없이 D2C 가격을 유지한 게 진짜 혁신이었고, 아마존·홀푸드 입점은 신뢰를 먼저 쌓은 다음에 따라온 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B0C2DCB188",
    image: "https://m.media-amazon.com/images/I/7126RO8oaaL._AC_SL1500_.jpg",
    otherUrl: "https://www.coterie.com",
  },
  {
    category: "diapering",
    nameEn: "Boogie No-Touch Diaper Rash Cream (with Spatula)",
    nameKo: "부기 노터치 기저귀 발진 크림 (스패츌러 포함)",
    noteEn: "The spatula applicator means the cream goes on the rash, not your fingertip — a one-part fix to the actual complaint people have about diaper cream. Not a reformulation, just better industrial design around the same paste.",
    noteKo: "스패츌러 어플리케이터 덕분에 크림이 손끝이 아니라 발진에 바로 발려요 — 기저귀 크림에 대한 진짜 불만을 한 가지 부품으로 해결했어요. 성분을 바꾼 게 아니라, 같은 크림을 감싸는 산업 디자인만 바꾼 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B0F3JPGJL3",
    image: "https://m.media-amazon.com/images/I/714pB+-gRvL._SL1500_.jpg",
  },
  {
    category: "diapering",
    nameEn: "Momcozy Baby Wipe Warmer",
    nameKo: "맘코지 물티슈 워머",
    noteEn: "Warms wipes to skin temperature, which sounds unnecessary until a 3am diaper change with a cold wipe wakes a sleeping baby back up. Competes purely on price and fast iteration rather than brand heritage — a newer entrant undercutting legacy nursery brands on nearly identical function.",
    noteKo: "물티슈를 체온과 비슷하게 데워주는데, 별거 아닌 것 같지만 새벽 3시에 차가운 물티슈로 깬 아기를 겪어보면 생각이 달라져요. 브랜드 헤리티지보다 가격과 빠른 제품 개선 속도로 경쟁하는, 기존 육아용품 브랜드를 가격으로 압박하는 신생 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B0CNP84VXZ",
    image: "https://m.media-amazon.com/images/I/5108p8PPNuL._SL1500_.jpg",
  },
  {
    category: "diapering",
    nameEn: "Skip Hop Baby Changing Pad",
    nameKo: "스킵합 기저귀 교환 패드",
    noteEn: "Wipeable surface means no fabric cover to strip and launder after every blowout — the design insight is that parents will pay more upfront to do less laundry later. A nursery-brand staple precisely because it solved a problem nobody else bothered naming.",
    noteKo: "물티슈로 닦기만 하면 되는 표면이라, 대참사 후에 커버를 벗겨서 세탁할 필요가 없어요 — '나중에 빨래를 덜 하기 위해 처음에 더 낸다'는 인사이트가 디자인의 전부예요. 아무도 굳이 이름 붙이지 않은 문제를 해결했기 때문에 육아용품 스테디셀러가 된 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B075X8TPMN",
    image: "https://m.media-amazon.com/images/I/51p15TmQfrL._SL1500_.jpg",
  },

  // ================= GEAR & ON-THE-GO · 외출/이동 =================
  {
    category: "gear",
    nameEn: "Graco SnugRide SnugFit 35 Infant Car Seat",
    nameKo: "그라코 스너그라이드 스너그핏 35 신생아 카시트",
    noteEn: "Clicks straight into the stroller frame without a separate adapter — one motion from car to stroller instead of waking a sleeping baby. A legacy brand's real advantage: the ecosystem compatibility a newer challenger brand can't match overnight.",
    noteKo: "별도 어댑터 없이 유모차 프레임에 바로 끼워져요 — 자던 아기를 깨우지 않고 차에서 유모차로 한 번에 옮길 수 있어요. 오래된 브랜드의 진짜 강점이 바로 이거예요 — 신생 브랜드가 하루아침에 따라올 수 없는 생태계 호환성이에요.",
    amazonUrl: "https://www.amazon.com/dp/B08K2X1DPC",
    image: "https://m.media-amazon.com/images/I/81InHEsi58L._SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "Cybex eGazelle S Stroller (+ Second Seat for Twins)",
    nameKo: "사이벡스 e가젤 S 유모차 (+쌍둥이용 세컨드 시트)",
    noteEn: "Electric assist turns a hill with two babies aboard into a non-event — you feel the weight disappear, the entire reason to pay a premium over a standard double stroller. German engineering applied to twin-stroller physics, a problem most brands just let parents suffer through.",
    noteKo: "전동 어시스트 덕분에 쌍둥이를 태우고 언덕을 올라도 무게가 사라지는 느낌이에요 — 일반 듀얼 유모차보다 훨씬 비싼 값을 하는 이유가 바로 이거예요. 대부분의 브랜드가 그냥 방치하는 '쌍둥이 유모차 물리학' 문제에 독일식 엔지니어링을 적용한 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0F48WKTRJ",
    image: "https://m.media-amazon.com/images/I/51HjfNck79L._SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "Baby Trend Snap-N-Go Double Stroller Frame",
    nameKo: "베이비트렌드 스냅앤고 더블 유모차 프레임",
    noteEn: "Two infant seats click onto a bare frame — cheap, light, and exactly as disposable-feeling as the price suggests. A good bridge product for the exact window before a real double stroller, and not a day longer.",
    noteKo: "신생아 카시트 두 개를 프레임에 그대로 끼워요 — 저렴하고 가벼운 만큼, 딱 그 가격대의 내구성이에요. 진짜 더블 유모차를 사기 전까지의 짧은 다리 역할로는 좋지만, 딱 그 기간까지만이에요.",
    reviewEn: "Honestly, we ended up using this very rarely.",
    reviewKo: "솔직히 말하면 저희는 거의 쓸 일이 없었어요.",
    amazonUrl: "https://www.amazon.com/dp/B008U4MKU6",
    image: "https://m.media-amazon.com/images/I/818lrmcX7HL._SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "Konny Baby Wrap Carrier Flex AirMesh",
    nameKo: "코니 아기띠 플렉스 에어메시",
    noteEn: "T-shirt-light fabric with zero buckles or rings to fumble with one-handed while holding a screaming baby — the whole Korean product philosophy here is subtraction, not addition. Packs into a pocket, which is the actual travel feature, not a marketing bullet point.",
    noteKo: "티셔츠처럼 가벼운 소재에 버클도 링도 없어서, 우는 아기를 안은 채 한 손으로도 헤매지 않아요 — 한국 브랜드다운 '더하기'가 아니라 '빼기'의 디자인 철학이에요. 주머니에 들어갈 만큼 작게 접혀서, 마케팅 문구가 아니라 진짜 여행 기능이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0B73KP572",
    image: "https://m.media-amazon.com/images/I/71tXtNff9QL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "Cosco Scenera NEXT Convertible Car Seat",
    nameKo: "코스코 시네라 넥스트 컨버터블 카시트",
    noteEn: "No frills, no fabric upgrades, no novelty cupholders — just a seat that passes the same federal crash standards as ones costing four times as much. Pure cost-leadership strategy, applied to a category parents are usually too anxious to price-shop.",
    noteKo: "고급 원단도, 예쁜 컵홀더도 없이 딱 카시트 본질만 있어요 — 그런데 네 배 비싼 카시트와 똑같은 연방 충돌 기준을 통과해요. 보통은 불안해서 가격 비교를 잘 안 하는 카테고리에 원가우위 전략을 적용한 제품이에요.",
    amazonUrl: "",
    otherUrl: "https://www.walmart.com/ip/Cosco-Kids-Scenera-NEXT-Convertible-Car-Seat-Otto-Infant-Toddler-Unisex/41126739",
    verdict: "essential",
    travel: true,
    valuePick: true,
  },
  {
    category: "gear",
    nameEn: "Cybex Libelle Ultra-Compact Stroller",
    nameKo: "사이벡스 리벨 초경량 휴대용 유모차",
    noteEn: "Folds one-handed into a shape small enough for an overhead bin — the German engineering flex here isn't ride quality, it's the fold mechanism. Becomes the default stroller almost by accident, because you stop reaching for the bigger one.",
    noteKo: "한 손으로 접으면 기내 선반에 들어갈 만큼 작아져요 — 여기서 독일 엔지니어링이 진짜 빛나는 건 승차감이 아니라 접히는 메커니즘이에요. 어느새 이게 기본 유모차가 돼버려요, 더 큰 유모차에 손이 안 가게 되니까요.",
    reviewEn: "Twin tip: with a stroller connector, one parent can push both alone.",
    reviewKo: "쌍둥이 팁: 유모차 커넥터로 두 대를 연결하면 혼자서도 둘 다 밀 수 있어요.",
    amazonUrl: "https://www.amazon.com/dp/B0B729KDCM",
    image: "https://m.media-amazon.com/images/I/51UhIdy6C4L._SL1000_.jpg",
    verdict: "essential",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "4moms MamaRoo Multi-Motion Baby Swing",
    nameKo: "포맘스 마마루 바운서 (스윙)",
    noteEn: "Five distinct motions mimicking actual parent movement, not just a generic swing arc — the tech-forward positioning (app control, motion sensors) justifies a price regular swings can't touch. Buys you twenty minutes of showering with both hands free, which alone pays for itself.",
    noteKo: "일반 그네처럼 뻔한 움직임이 아니라, 실제 부모의 움직임을 흉내낸 다섯 가지 모션이에요 — 앱 조작, 모션 센서 같은 테크 포지셔닝이 일반 바운서보다 비싼 가격을 정당화해요. 양손이 자유로운 20분간의 샤워를 벌어주는 것만으로도 값을 해요.",
    amazonUrl: "https://www.amazon.com/dp/B0B3F93NYT",
    image: "https://m.media-amazon.com/images/I/41rBMT5sHGL._SL1232_.jpg",
  },
  {
    category: "gear",
    nameEn: "BabyBjörn Bouncer Balance Soft",
    nameKo: "베이비뵨 바운서 밸런스 소프트",
    noteEn: "No batteries, no motor — baby's own movement makes it bounce, either delightfully minimal or a missed opportunity depending on your appetite for tech. Folds flat enough to travel with, which the motorized competitors mostly can't match.",
    noteKo: "배터리도 모터도 없이, 아기 스스로의 움직임으로 흔들려요 — 테크에 대한 취향에 따라 매력적인 미니멀리즘일 수도, 아쉬운 부분일 수도 있어요. 모터 달린 경쟁 제품들은 대부분 못 하는, 납작하게 접혀 휴대 가능한 폼팩터예요.",
    amazonUrl: "https://www.amazon.com/dp/B016DAWD2S",
    image: "https://m.media-amazon.com/images/I/61XS-3NqoBL._SL1500_.jpg",
    verdict: "essential",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "Tushbaby Hip Seat Carrier",
    nameKo: "터쉬베이비 힙시트",
    noteEn: "A padded shelf at hip height means your arm stops being the load-bearing structure — the ergonomic case is simple and it works, no straps required for a quick pickup. Solves the in-between phase when they're too heavy to carry casually but not ready for a full carrier.",
    noteKo: "엉덩이 높이의 패딩 선반이 팔 대신 무게를 받쳐줘요 — 별도 캐리어 없이도 금방 안아 올릴 수 있는, 단순하지만 확실한 인체공학이에요. 캐주얼하게 안기엔 무겁고 풀 캐리어를 쓰기엔 애매한, 딱 그 중간 시기를 해결해줘요.",
    amazonUrl: "https://www.amazon.com/dp/B07R4C4VFX",
    image: "https://m.media-amazon.com/images/I/81ufYbV27NL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "Baby Trend Navigator 2-in-1 Stroller Wagon",
    nameKo: "베이비트렌드 네비게이터 2-in-1 스트롤러 왜건",
    noteEn: "A wagon-stroller hybrid that fits two toddlers and a day's worth of park gear — the category exists because neither pure wagons nor pure strollers solved the twin-outing logistics problem. Bulky to store, the honest trade-off for the capacity.",
    noteKo: "왜건과 유모차를 합친 제품으로, 아이 둘과 하루치 나들이 짐이 다 들어가요 — 순수 왜건도 순수 유모차도 쌍둥이 외출 문제를 못 풀어서 생긴 카테고리예요. 수납 공간을 많이 차지하는 게, 이 수용력에 대한 솔직한 트레이드오프예요.",
    amazonUrl: "https://www.amazon.com/dp/B0G1ZF9Z63",
    image: "https://m.media-amazon.com/images/I/715k1UOSa3L._SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "RideSafer Gen 5 Wearable Car Seat (XS)",
    nameKo: "라이드세이퍼 젠5 착용형 카시트 (XS)",
    noteEn: "A car seat you wear instead of install — folds into a backpack, which matters enormously in the third taxi of a trip with no car seat in sight. Trades some structural protection of a hard-shell seat for radical portability; check the safety literature before deciding if that trade works for you.",
    noteKo: "설치하는 게 아니라 입히는 카시트예요 — 백팩에 들어가서, 카시트 없는 택시를 세 번째 타는 순간 진가를 발휘해요. 하드쉘 카시트의 구조적 보호 일부를 포기하는 대신 휴대성을 얻는 트레이드오프이니, 결정 전에 안전성 자료를 꼭 확인하세요.",
    amazonUrl: "https://www.amazon.com/dp/B0CYNNYLB2",
    image: "https://m.media-amazon.com/images/I/81N5plNyGUL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "Munchkin Brica Magnetic Car Window Shade",
    nameKo: "먼치킨 브리카 자석식 차량 햇빛가리개",
    noteEn: "Magnetic mount instead of suction cups, so it doesn't peel off and fall onto a napping baby's face mid-drive — a small fix for a genuinely annoying failure mode of every cheaper shade. Munchkin's usual move: find the one thing that breaks, fix just that.",
    noteKo: "흡착판이 아니라 자석식이라, 운전 중에 뚝 떨어져 낮잠 자는 아기 얼굴을 덮는 일이 없어요 — 저가 제품들의 진짜 짜증나는 실패 지점을 딱 하나 고친 거예요. 뭐가 고장 나는지 찾아서 그것만 고치는, 먼치킨다운 접근이에요.",
    amazonUrl: "https://www.amazon.com/dp/B07ZPMHYVB",
    image: "https://m.media-amazon.com/images/I/81TQAR8xpbL._AC_SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "Dream On Me Zodiak Playard",
    nameKo: "드림온미 조디악 플레이야드 (휴대용 아기침대)",
    noteEn: "Lighter and cheaper than the premium travel-crib brands, with a mesh build that packs down fast — trading a bit of plushness for a lot less weight in the trunk. The budget alternative that does the one job without the premium markup.",
    noteKo: "프리미엄 여행용 침대 브랜드보다 가볍고 저렴하면서, 메쉬 소재라 빨리 접혀요 — 약간의 푹신함을 포기하는 대신 트렁크 공간과 무게를 많이 아껴요. 프리미엄 마크업 없이 '집 밖에서 안전하게 재우기'라는 한 가지 일만 하는 예산형 대안이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0D9Y7GM8V",
    image: "https://m.media-amazon.com/images/I/81sxYYZgJTL._SL1500_.jpg",
    travel: true,
  },
  {
    category: "gear",
    nameEn: "7AM Enfant Blanket 212 Evolution Footmuff",
    nameKo: "세븐에이엠 앙팡 212 에볼루션 풋머프",
    noteEn: "Zips directly into the stroller seat, turning it into a sleeping bag on wheels for real winter — not the thin fleece liners most brands sell as 'weatherproofing.' A niche New York label that survives by being genuinely better at one narrow, seasonal job.",
    noteKo: "유모차 시트에 바로 지퍼로 채워져서, 진짜 겨울용 침낭이 돼요 — 다른 브랜드들이 '방한'이라고 파는 얇은 플리스 라이너와는 달라요. 좁고 계절적인 한 가지 일을 진짜 잘해서 살아남는, 뉴욕의 니치 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B006BEPLM6",
    image: "https://m.media-amazon.com/images/I/81J82diVw2L._SL1500_.jpg",
    otherUrl: "https://www.bloomingdales.com/shop/product/7am-enfant-blanket-212-evolution-footmuff?ID=4310062",
  },
  {
    category: "gear",
    nameEn: "7AM Enfant Classic Warmmuffs (Stroller Hand Muffs)",
    nameKo: "세븐에이엠 앙팡 유모차 핸드머프",
    noteEn: "Solves the specific problem of pushing a stroller in freezing weather without ski gloves clumsily gripping the bar — a companion accessory riding on the footmuff's reputation. Narrow use case, but there's no real substitute when you need it.",
    noteKo: "스키 장갑을 낀 손으로 어색하게 유모차를 미는 대신, 추운 날씨에 편하게 밀 수 있게 해줘요 — 풋머프의 명성에 올라탄 동반 액세서리예요. 쓰임새는 좁지만, 필요할 땐 딱히 대체품이 없어요.",
    amazonUrl: "https://www.amazon.com/dp/B008VUMKF4",
    image: "https://m.media-amazon.com/images/I/61cy-zXkyzL._SL1448_.jpg",
    otherUrl: "https://www.bloomingdales.com/shop/product/7am-enfant-classic-warmmuffs?ID=3667796",
  },
  {
    category: "gear",
    nameEn: "Guava Family Lotus Travel Crib & Playpen",
    nameKo: "구아바 로터스 여행용 아기침대 겸 플레이펜",
    noteEn: "Folds into its own backpack and sets up in under a minute — the entire product thesis is 'a travel crib that doesn't feel like a punishment to carry.' Costs more than budget playards, and the backpack fold is the entire reason why.",
    noteKo: "자기 백팩 안으로 접혀서 1분 안에 조립돼요 — '들고 다니는 게 벌 받는 느낌이 아닌 여행용 침대'라는 게 이 제품의 전부예요. 저가 플레이야드보다 비싼데, 그 이유가 바로 이 백팩 폴딩이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00AKKDSNG",
    image: "https://m.media-amazon.com/images/I/91H2PBkZELL._SL1500_.jpg",
    travel: true,
  },

  // ================= HEALTH · 건강 =================
  {
    category: "health",
    nameEn: "Frida Baby Medi Pacifier (Medicine Dispenser)",
    nameKo: "프리다 베이비 메디 쪽쪽이 (투약 젖꼭지)",
    noteEn: "Medicine dispenses through a pacifier's suction motion instead of a syringe fight — Frida built an entire brand on solving unglamorous baby problems nobody wanted to name out loud. The category-defining move: make the ugly parenting moments worth a premium price.",
    noteKo: "주사기 씨름 대신 쪽쪽이 빠는 동작으로 약이 나와요 — 프리다는 아무도 입 밖에 내고 싶어하지 않던 육아의 지저분한 문제들을 해결하며 브랜드 전체를 세웠어요. '못생긴 육아 순간'을 프리미엄 가격을 받을 만한 디자인 카테고리로 만든 게 핵심이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0CCSX6KPL",
    image: "https://m.media-amazon.com/images/I/515RG+fK+UL._SL1001_.jpg",
    verdict: "essential",
  },
  {
    category: "health",
    nameEn: "Frida Baby NoseFrida SnotSucker (Manual Nasal Aspirator)",
    nameKo: "프리다 베이비 노즈프리다 콧물흡입기 (수동)",
    noteEn: "Manual suction sounds worse than it is — you control the pressure with your own breath, oddly more effective and less scary to a baby than an electric buzz. The original product that built Frida Baby's whole brand identity around 'gross but it works.'",
    noteKo: "수동 흡입이라니 이상하게 들리지만, 본인 호흡으로 압력을 조절하니 오히려 전동식보다 효과적이고 아기도 덜 놀라요. '더럽지만 효과는 확실하다'는 프리다 베이비 브랜드 정체성을 만든 원조 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00171WXII",
    image: "https://m.media-amazon.com/images/I/71x9h8NxWnL._SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Little Remedies New Baby Essentials Kit",
    nameKo: "리틀 레머디스 신생아 상비약 키트",
    noteEn: "A starter bundle so you're not making six separate first-week pharmacy runs while sleep-deprived — the value here is decision-reduction, not any single product being exceptional. Solid, unglamorous, does what the label says.",
    noteKo: "잠도 못 자는 첫 주에 약국을 여섯 번 따로 다녀오지 않아도 되는 스타터 번들이에요 — 어느 한 제품이 특별해서가 아니라, 결정을 줄여준다는 데 가치가 있어요. 화려하진 않지만 라벨에 적힌 대로 확실히 해줘요.",
    amazonUrl: "https://www.amazon.com/dp/B075G6XMSF",
    image: "https://m.media-amazon.com/images/I/71unkU1g-CL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Mommy's Bliss Baby Probiotic Drops",
    nameKo: "마미스 블리스 유아 유산균 드롭",
    noteEn: "Daily drops rather than a dramatic single fix — the honest expectation is that this helps at the margins with gas and colic, not that it's a cure. Long-established brand trust carries this one more than any novel formulation.",
    noteKo: "극적인 한 방 해결책이 아니라 매일 챙기는 드롭이에요 — 배앓이와 가스를 극적으로 없애준다기보다 조금씩 도와준다는 정직한 기대치예요. 혁신적인 성분보다는 오래 쌓인 브랜드 신뢰가 더 크게 작용하는 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00TGHNNES",
    image: "https://m.media-amazon.com/images/I/71Wg7bu9hbL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Momcozy Electric Baby Nail Buffer",
    nameKo: "맘코지 전동 아기 손톱 트리머",
    noteEn: "Files instead of clips, which matters a lot when clipping a sleeping newborn's paper-thin nails feels like a surgical procedure. Same pattern as the wipe warmer — a fast-follower brand solving a real problem cheaply, not inventing a new one.",
    noteKo: "손톱깎이 대신 갈아주는 방식이라, 자는 신생아의 종잇장 같은 손톱을 깎는 게 수술처럼 느껴질 때 정말 도움이 돼요. 물티슈 워머와 같은 패턴이에요 — 새로운 걸 발명하기보다, 진짜 문제를 저렴하게 잘 풀어내는 패스트팔로워 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B0CL4G33BX",
    image: "https://m.media-amazon.com/images/I/61OOPeG2c-L._SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Jordan Step 1 Baby Toothbrush (4-Pack)",
    nameKo: "조르단 1단계 아기 칫솔 (4개)",
    noteEn: "Soft bristles and a handle sized for a parent's grip, not the child's — the honest design admission that a baby's first toothbrush is really a tool for the adult holding it. A century-old Norwegian oral-care brand exporting quietly, without much marketing spend.",
    noteKo: "부드러운 칫솔모와, 아이가 아니라 부모의 손에 맞춘 손잡이 크기예요 — 아기의 첫 칫솔은 사실 그걸 쥐는 어른을 위한 도구라는 솔직한 디자인 인정이에요. 마케팅비를 많이 쓰지 않고도 조용히 수출되는, 100년 역사의 노르웨이 구강관리 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B01CKKOIZU",
    image: "https://m.media-amazon.com/images/I/71scbPZyIKL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Pigeon Baby Nail Clipper (9m+)",
    nameKo: "피죤 아기 손톱깎이 (9개월+)",
    noteEn: "The splatter-proof case physically catches clippings mid-air — a small mechanical detail Japanese product design treats as non-negotiable and most competitors skip entirely. You only appreciate it the first time you're not picking nail bits off the changing pad.",
    noteKo: "튄 손톱 조각을 케이스가 물리적으로 받아줘요 — 일본 제품 디자인이 절대 타협하지 않는 작은 디테일인데, 경쟁 제품 대부분은 그냥 생략해요. 교환대에서 손톱 조각을 줍지 않아도 되는 첫 순간에야 그 가치를 깨닫게 돼요.",
    amazonUrl: "https://www.amazon.com/dp/B09Q5YF2BS",
    image: "https://m.media-amazon.com/images/I/61+0D-Gk-TL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Tommee Tippee Electric Nail File",
    nameKo: "토미티피 전동 손톱 파일",
    noteEn: "Six interchangeable filing heads mean one device covers the whole family, not just the baby — broader positioning than most single-purpose baby-nail tools. A UK brand that built its reputation on bottles before expanding sideways into this.",
    noteKo: "교체 가능한 필링 헤드 6종으로 아기뿐 아니라 온 가족이 함께 써요 — 대부분의 단일 용도 아기 손톱 도구보다 넓은 포지셔닝이에요. 젖병으로 명성을 쌓은 뒤 옆으로 카테고리를 확장한 영국 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B09NDTRCYD",
    image: "https://m.media-amazon.com/images/I/71oDfUFNqUL._SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Feverall Infant Acetaminophen Suppositories",
    nameKo: "피버올 유아 해열 좌약",
    noteEn: "For the specific and miserable scenario where a feverish baby won't keep oral medicine down — a narrow use case that exists precisely because parents needed it once and were grateful it did the job. Not a brand you build loyalty around; a product you're relieved exists. Check with your pediatrician.",
    noteKo: "열이 나는 아기가 먹는 약을 자꾸 게워낼 때를 위한, 좁고 생각하고 싶지 않은 상황을 위한 제품이에요 — 딱 한 번 필요했다가 다행히 있어줘서 고마웠던 경험 때문에 존재하는 카테고리예요. 브랜드 충성도를 쌓는 제품이라기보다, 존재해줘서 안심이 되는 제품이에요. 소아과와 상의 후 사용하세요.",
    amazonUrl: "https://www.amazon.com/dp/B00Q9BH6O2",
    image: "https://m.media-amazon.com/images/I/61GHy-1EjzL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Infants' Tylenol (Dye-Free)",
    nameKo: "유아용 타이레놀 (무색소)",
    noteEn: "The default fever reducer precisely because it's the default — decades of pediatrician recommendation is a moat no challenger brand can shortcut. The dosing syringe is the actual UX improvement over a spoon; don't lose it.",
    noteKo: "이게 기본값인 이유는 정말 기본값이기 때문이에요 — 수십 년간 쌓인 소아과 추천이라는, 어떤 신생 브랜드도 지름길로 따라올 수 없는 해자예요. 계량 스푼보다 계량 주사기가 실질적인 UX 개선이니 잃어버리지 마세요.",
    amazonUrl: "https://www.amazon.com/dp/B073Q34KKQ",
    image: "https://m.media-amazon.com/images/I/81tl9e7QtsL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Herb Pharm Kids Immune Fortifier",
    nameKo: "허브팜 키즈 면역 시럽",
    noteEn: "Alcohol-free elderberry drops for the daycare-cold gauntlet — positioned as a gentler, more 'natural' alternative for parents wary of every-week medicating. Efficacy evidence for elderberry is mixed in the literature; you're buying into a wellness narrative as much as a product.",
    noteKo: "어린이집 감기 시즌을 위한 무알코올 엘더베리 드롭이에요 — 매주 약을 먹이기 꺼려지는 부모를 위한 좀 더 '자연스러운' 대안으로 포지셔닝돼 있어요. 엘더베리의 실제 효능에 대한 연구 결과는 엇갈리니, 제품만큼이나 웰니스 서사를 사는 셈이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0199RDWOK",
    image: "https://m.media-amazon.com/images/I/71InSZSqZgL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "ChildLife Essentials Liquid Multivitamin",
    nameKo: "차일드라이프 액상 종합비타민",
    noteEn: "Liquid format mixes into milk or water without a fight over a chewable tablet — the format is the entire innovation, not the vitamin content itself. Orange-mango flavoring does the actual heavy lifting of compliance.",
    noteKo: "액상 형태라 씹는 정제와 실랑이 없이 우유나 물에 섞여요 — 비타민 성분 자체보다 이 액상 포맷이 진짜 혁신이에요. 오렌지 망고 향이 실제로 아이가 거부감 없이 먹게 만드는 핵심 요소예요.",
    amazonUrl: "https://www.amazon.com/dp/B001E123JA",
    image: "https://m.media-amazon.com/images/I/71MNpeV38qL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "BioGaia Immune Active Baby Probiotic Drops + Vitamin D",
    nameKo: "바이오가이아 유산균 + 비타민D 드롭",
    noteEn: "Combines probiotic and vitamin D into a single dropper — one bottle instead of two on the counter, the whole value proposition when you're already juggling a dozen daily tasks. A Swedish biotech pedigree lending clinical credibility that supplement-aisle brands usually lack.",
    noteKo: "유산균과 비타민D를 드롭 하나에 합쳤어요 — 카운터 위에 병 두 개 대신 하나, 매일 열두 가지를 저글링하는 부모에겐 그게 전부예요. 스웨덴 바이오테크 혈통이 일반 서플리먼트 브랜드에는 없는 임상적 신뢰도를 더해줘요.",
    amazonUrl: "https://www.amazon.com/dp/B09H3PTZSK",
    image: "https://m.media-amazon.com/images/I/71eJGbV-7RL._AC_SL1500_.jpg",
  },
  {
    category: "health",
    nameEn: "Tru Earth Baby Laundry Detergent Sheets",
    nameKo: "트루얼스 아기 세탁 세제 시트",
    noteEn: "Ships flat as paper sheets instead of a heavy plastic jug — a genuine packaging and shipping-cost innovation dressed up as an eco-story, and it happens to also be true. No measuring cup means no over-pouring, which is where most people waste detergent anyway.",
    noteKo: "무거운 플라스틱 통 대신 종이처럼 납작하게 배송돼요 — 친환경 스토리로 포장돼 있지만, 실제로 포장·배송 비용을 줄이는 진짜 혁신이기도 해요. 계량컵이 없으니 과다 투입도 없는데, 사실 대부분의 세제 낭비가 거기서 나와요.",
    amazonUrl: "https://www.amazon.com/dp/B08DLDJG2K",
    image: "https://m.media-amazon.com/images/I/71ue9PajvOL._AC_SL1500_.jpg",
  },

  // ================= SAFETY · 안전 =================
  {
    category: "safety",
    nameEn: "EZIGO Extra-Wide Retractable Baby Gate (120\")",
    nameKo: "이지고 초광폭 리트랙터블 안전문 (약 3m)",
    noteEn: "Retractable mesh spans doorways most rigid gates can't fit, and rolls away invisibly when not in use — solves the specific problem of oddly wide openings that standard gates just fail at. Generic-brand execution of a well-understood category; nothing wrong with that.",
    noteKo: "일반 안전문이 못 막는 이상하게 넓은 개구부까지 메쉬가 늘어나고, 안 쓸 땐 눈에 안 띄게 말려 들어가요 — 표준 안전문이 그냥 포기하는 특이한 구조 문제를 해결해요. 이미 잘 알려진 카테고리를 무난하게 실행한 제품이고, 그거면 충분해요.",
    amazonUrl: "https://www.amazon.com/dp/B0DWWMQ2Y3",
    image: "https://m.media-amazon.com/images/I/811VGRmklKL._AC_SL1500_.jpg",
  },
  {
    category: "safety",
    nameEn: "Compact Fire Extinguisher Spray (2-Pack)",
    nameKo: "가정용 소화 스프레이 (2개)",
    noteEn: "Small enough to keep in a kitchen drawer instead of mounted on a wall like an industrial extinguisher — the design trade-off is capacity for approachability. You're buying peace of mind you hope to never redeem.",
    noteKo: "산업용 소화기처럼 벽에 걸어두는 대신 주방 서랍에 넣어둘 만큼 작아요 — 용량 대신 접근성을 택한 디자인 트레이드오프예요. 절대 쓸 일이 없기를 바라며 사는 마음의 평화예요.",
    amazonUrl: "https://www.amazon.com/dp/B0DH5CM2CC",
    image: "https://m.media-amazon.com/images/I/71rRnzqT3+L._SL1500_.jpg",
  },
  {
    category: "safety",
    nameEn: "Emergency Fire Blanket (4-Pack)",
    nameKo: "화재 진압 담요 (4장)",
    noteEn: "Cheaper and simpler than an extinguisher, with zero moving parts to fail — the trade-off is it only works on small, smotherable fires, not anything that's spread. A category where the low-tech option genuinely is the right one for most home kitchens.",
    noteKo: "소화기보다 저렴하고 단순하며, 고장 날 부품이 하나도 없어요 — 대신 이미 번진 불이 아니라 초기의 작은 불에만 효과가 있어요. 대부분의 가정 주방엔 로우테크 옵션이 오히려 정답인 카테고리예요.",
    amazonUrl: "https://www.amazon.com/dp/B0BVZ8NB1J",
    image: "https://m.media-amazon.com/images/I/81Tz6tDrINL._AC_SL1500_.jpg",
  },
  {
    category: "safety",
    nameEn: "Toddler Life Jacket (USCG-Approved, 20–30 lbs)",
    nameKo: "유아 구명조끼 (미 해안경비대 인증)",
    noteEn: "USCG-approved fit for a very specific weight range — the entire product is regulatory compliance plus a size range other jackets skip. Not a fashion purchase; check the certification, not the color.",
    noteKo: "미 해안경비대 인증을 받은, 아주 구체적인 체중 범위에 맞는 제품이에요 — 다른 구명조끼들이 건너뛰는 사이즈 구간을 규정 준수와 함께 채워줘요. 디자인이 아니라 인증을 보고 사야 하는 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0DQ57XS9R",
    image: "https://m.media-amazon.com/images/I/71gnfHmBduL._AC_SL1500_.jpg",
  },

  // ================= BATH · 목욕 =================
  {
    category: "bathing",
    nameEn: "Angelcare Baby Bath Support",
    nameKo: "엔젤케어 목욕 지지대",
    noteEn: "A mesh sling suspends a slippery newborn at an angle where both your hands are free instead of one arm doing all the holding — the ergonomics are the entire product. Priced like a commodity item despite solving a genuinely stressful daily moment.",
    noteKo: "메쉬 슬링이 미끄러운 신생아를 각도에 맞춰 받쳐줘서, 한 팔로 다 붙잡는 대신 두 손이 자유로워져요 — 인체공학이 이 제품의 전부예요. 매일 스트레스받는 순간을 해결해주는데도 일반 소모품처럼 저렴한 가격이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0DTWXK9J9",
    image: "https://m.media-amazon.com/images/I/61U3DpK2haL._SL1500_.jpg",
    verdict: "essential",
    valuePick: true,
  },
  {
    category: "bathing",
    nameEn: "Mustela Newborn Baby Arrival Gift Set",
    nameKo: "무스텔라 신생아 스킨케어 세트",
    noteEn: "Cleanser, lotion, and diaper cream formulated together rather than separately, so the ingredient philosophy stays consistent across your whole routine. French pharmacy-brand positioning: clinical credibility with none of the clinical packaging.",
    noteKo: "클렌저, 로션, 발진 크림을 따로가 아니라 하나의 철학으로 만들어서, 성분 원칙이 전체 루틴에 일관되게 적용돼요. 프랑스 약국 브랜드 포지셔닝 — 임상적 신뢰도는 있지만 병원 느낌의 포장은 없어요.",
    amazonUrl: "https://www.amazon.com/dp/B01NA7ZMIA",
    image: "https://m.media-amazon.com/images/I/71Vfx36c+hL._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "bathing",
    nameEn: "Mustela Liniment No-Rinse Cleanser",
    nameKo: "무스텔라 리니먼트 노린스 클렌저",
    noteEn: "Skips the rinse step of a diaper-change cleanse entirely — one less thing to do at 3am, and the olive-oil base is gentle enough that dermatologists don't push back on it. Same French formulation philosophy as the gift set, unbundled into a single product.",
    noteKo: "기저귀 교체 클렌징에서 헹구는 단계를 아예 없애줘요 — 새벽 3시에 할 일이 하나 줄어들고, 올리브오일 베이스라 피부과 의사들도 딱히 반대하지 않을 만큼 순해요. 기프트 세트와 같은 프랑스식 포뮬레이션 철학을, 단품으로 뽑아낸 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00WX699SI",
    image: "https://m.media-amazon.com/images/I/61rUTBoQCBL._SL1500_.jpg",
  },
  {
    category: "bathing",
    nameEn: "BambooBebe Gauze Washcloths (10-Pack)",
    nameKo: "밤부베베 거즈 손수건 (10장)",
    noteEn: "Loosely woven gauze that's softer against newborn skin than terry-cloth washcloths and dries faster — a Korean nursery staple that Western baby registries mostly overlook entirely. Once you switch, ordinary washcloths feel rough by comparison.",
    noteKo: "성글게 짠 거즈 소재라 일반 타월 손수건보다 신생아 피부에 더 부드럽고 빨리 말라요 — 서구권 베이비 레지스트리에서는 대체로 놓치는 한국 육아 필수템이에요. 한번 써보면 일반 손수건이 오히려 거칠게 느껴져요.",
    amazonUrl: "https://www.amazon.com/dp/B0BLQ4X9T9",
    image: "https://m.media-amazon.com/images/I/41fw+OOM4jL._SL1000_.jpg",
  },
  {
    category: "bathing",
    nameEn: "California Baby Calendula Cream",
    nameKo: "캘리포니아 베이비 카렌듈라 크림",
    noteEn: "Plant-based formulation for dry patches and sensitive skin — positioned in the 'clean beauty for babies' niche that charges a premium for ingredient transparency more than dramatic performance differences. You're buying the ingredient list as much as the cream.",
    noteKo: "건조한 부위와 민감성 피부를 위한 식물성 포뮬레이션이에요 — 극적인 효과 차이보다는 성분 투명성에 프리미엄을 매기는 '클린 뷰티 포 베이비' 니치에 자리한 브랜드예요. 크림 자체만큼이나 성분표를 사는 셈이에요.",
    amazonUrl: "https://www.amazon.com/dp/B00R60FY3U",
    image: "https://m.media-amazon.com/images/I/71iwHc6Yx4L._SL1500_.jpg",
  },

  // ================= PLAY · 놀이 =================
  {
    category: "playing",
    nameEn: "Lovevery Play Gym",
    nameKo: "러브에버리 플레이 짐",
    noteEn: "Stage-based design means the same base mat gets new attachments as development milestones hit, instead of buying an entirely new toy every few months. The subscription-adjacent model — matching toys to age — is the real innovation, not any single plush attachment.",
    noteKo: "발달 단계에 맞춰 같은 매트에 새 부속품이 추가되는 구조라, 몇 달마다 새 장난감을 통째로 사지 않아도 돼요. 연령에 맞춰 장난감을 매칭해주는 구독형에 가까운 모델이, 개별 플러시 부속품보다 진짜 브랜드의 혁신이에요.",
    amazonUrl: "https://www.amazon.com/dp/B075R8BXXC",
    image: "https://m.media-amazon.com/images/I/81oh+4OZH1L._SL1500_.jpg",
    verdict: "essential",
  },
  {
    category: "playing",
    nameEn: "Bumbo Floor Seat PLUS",
    nameKo: "범보 플로어 시트 플러스",
    noteEn: "Molded foam seat that props up an early sitter before core strength fully arrives — a South African design that became a default nursery item almost by accident, then got copied by everyone. The tray is the upsell; the seat alone is the actual product.",
    noteKo: "코어 근력이 완전히 자리잡기 전, 이른 시기의 앉기를 도와주는 폼 성형 시트예요 — 남아공에서 디자인됐다가 거의 우연히 육아용품 기본템이 되고, 이후 모두가 따라 만들었어요. 트레이는 업셀이고, 진짜 제품은 시트 자체예요.",
    amazonUrl: "https://www.amazon.com/dp/B0F19HC32G",
    image: "https://m.media-amazon.com/images/I/61ejYkJ9blL._SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "IKEA Cirkustält Kids Play Tent",
    nameKo: "이케아 시르쿠스텔트 키즈 플레이 텐트",
    noteEn: "Flat-packed, cheap, and exactly as sturdy as a budget tent should be — no pretense, no premium positioning, just IKEA's usual formula of good-enough design at a price that doesn't require justification. Becomes a nursery's most-used object for reasons no design brief could predict.",
    noteKo: "납작하게 포장돼 오고, 저렴하고, 딱 그 가격만큼 튼튼해요 — 프리미엄인 척하지 않고, 정당화가 필요 없는 가격에 적당히 좋은 디자인이라는 이케아의 늘 그 공식이에요. 어떤 디자인 기획서도 예측 못 할 이유로 아기방에서 제일 자주 쓰는 물건이 돼요.",
    amazonUrl: "",
    otherUrl: "https://www.ikea.com/us/en/p/cirkustaelt-childrens-tent-red-blue-white-60581369/",
  },
  {
    category: "playing",
    nameEn: "Jack Musical Baby Crib Mobile",
    nameKo: "잭 뮤지컬 크립 모빌",
    noteEn: "Slow rotation and a soft lullaby, sold exclusively through Pottery Barn Kids' higher-margin nursery channel rather than mass retail — you're paying interior-decor prices for a mechanism any brand could build. Worth it only if the aesthetic match to a coordinated nursery matters to you. Not on Amazon.",
    noteKo: "느린 회전과 잔잔한 자장가 — 대형 유통이 아니라 포터리반 키즈의 고마진 인테리어 채널로만 파는, 사실 어느 브랜드든 만들 수 있는 메커니즘에 인테리어 가격을 매긴 제품이에요. 아기방 톤을 맞추는 게 중요한 사람에게만 그 값을 해요. 아마존에는 없어요.",
    amazonUrl: "",
    otherUrl: "https://www.potterybarnkids.com/products/jack-musical-crib-mobile/",
  },
  {
    category: "playing",
    nameEn: "Bright Starts Oball Easy Grasp Ball",
    nameKo: "오볼 클래식",
    noteEn: "Open lattice design means fingers that can't yet grip a solid ball can still hook onto it — one geometric idea, executed cheaply, never really improved on since. Copied constantly; rarely bettered.",
    noteKo: "격자무늬 구조라 아직 물건을 완전히 못 쥐는 손도 걸어서 잡을 수 있어요 — 하나의 기하학적 아이디어가 제품의 전부고, 저렴하게 실행된 이후로 딱히 개선될 필요가 없었어요. 계속 카피되지만, 더 나아지는 경우는 드물어요.",
    amazonUrl: "https://www.amazon.com/dp/B00ZRD99C0",
    image: "https://m.media-amazon.com/images/I/71BFqKPjRBL._SL1500_.jpg",
    valuePick: true,
  },
  {
    category: "playing",
    nameEn: "Bright Starts Lots of Links (24-Count)",
    nameKo: "브라이트스타츠 링 장난감 (24개)",
    noteEn: "A bag of plastic rings solving the universal toddler problem of dropped toys — not clever, just endlessly useful, priced like the commodity it basically is. The value-pick logic in one product: nobody needs a premium version of a plastic ring.",
    noteKo: "플라스틱 링 한 봉지가 장난감을 계속 떨어뜨리는 흔한 문제를 해결해줘요 — 특별히 영리하진 않지만 끝없이 유용하고, 딱 그 정도 가격이에요. '플라스틱 링의 프리미엄 버전은 아무도 필요 없다'는 가성비 로직 그 자체예요.",
    amazonUrl: "https://www.amazon.com/dp/B001ABZGU2",
    image: "https://m.media-amazon.com/images/I/61IljL-cdnL._SL1289_.jpg",
    valuePick: true,
  },
  {
    category: "playing",
    nameEn: "Toniebox 2 Starter Set",
    nameKo: "토니박스 2 스타터 세트",
    noteEn: "A screen-free audio player toddlers operate themselves by placing a figurine on top — the entire brand thesis is that parents will pay a premium to keep a screen out of the room during storytime. The figurines, sold separately and repeatedly, are where the real business model lives.",
    noteKo: "화면 없이, 아이가 스스로 피규어를 올려서 조작하는 오디오 플레이어예요 — 스토리타임에 화면을 안 들이기 위해 프리미엄을 지불할 부모를 겨냥한 게 브랜드의 전부예요. 진짜 비즈니스 모델은 따로 사야 하는 피규어들에 있어요.",
    amazonUrl: "https://www.amazon.com/dp/B0FJ3R4FBX",
    image: "https://m.media-amazon.com/images/I/61ohsQRpgVL._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Tonies Creative Character",
    nameKo: "토니 크리에이티브 캐릭터",
    noteEn: "Record your own voice reading a story, so a grandparent's voice plays back on demand — the emotional positioning does more work than the audio quality. Each figure is a small, recurring purchase; that's by design, not accident.",
    noteKo: "직접 목소리를 녹음해서, 조부모님 목소리로 언제든 이야기를 들려줄 수 있어요 — 음질보다 감정적 포지셔닝이 훨씬 크게 작용해요. 피규어 하나하나가 반복 구매를 유도하는 작은 상품인데, 이건 우연이 아니라 설계예요.",
    amazonUrl: "https://www.amazon.com/dp/B0B6G27X9F",
    image: "https://m.media-amazon.com/images/I/714YS9nd7GL._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Veggie Baby Edible Finger Paint",
    nameKo: "먹어도 되는 채소 핑거페인트",
    noteEn: "Vegetable-based pigment safe enough for a baby who treats art supplies as a snack — the entire value proposition is peace of mind during the inevitable taste-test. Not as vivid as synthetic paint, the honest trade-off for edibility.",
    noteKo: "미술 도구를 간식처럼 대하는 아기도 안심할 수 있는 채소 기반 색소예요 — 결국 벌어질 맛보기 순간에 대한 마음의 평화가 이 제품의 전부예요. 합성 물감만큼 색이 선명하진 않은데, 먹어도 되는 것에 대한 정직한 트레이드오프예요.",
    amazonUrl: "https://www.amazon.com/dp/B07TKFGP1M",
    image: "https://m.media-amazon.com/images/I/81BHva89QrL._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Flexible Flyer Baby Pull Sled",
    nameKo: "플렉시블 플라이어 유아 눈썰매",
    noteEn: "A classic pull-sled shape that hasn't changed much in decades, because it didn't need to — a toddler seat bolted onto a design that already worked. Nostalgia-driven purchase as much as a functional one.",
    noteKo: "수십 년간 크게 바뀌지 않은 클래식 눈썰매 모양이에요 — 바뀔 필요가 없었으니까요. 이미 잘 작동하는 디자인에 유아용 좌석만 얹은 거예요. 기능만큼이나 향수를 사는 제품이에요.",
    amazonUrl: "https://www.amazon.com/dp/B000LF8XSU",
    image: "https://m.media-amazon.com/images/I/61NmqGwRPCL._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Inflatable Baby Support Seat",
    nameKo: "유아 인플레터블 소파 (앉기 연습)",
    noteEn: "Blow-up and deflate on demand, so it takes up almost no luggage space — the design bet is portability over durability, and for a seat used for a few months, that's the right bet. Not built to last years; built to pack flat.",
    noteKo: "필요할 때 불고 뺄 수 있어서 짐 공간을 거의 차지하지 않아요 — 내구성보다 휴대성을 택한 디자인 판단인데, 몇 달만 쓸 제품이니 맞는 선택이에요. 몇 년을 버티도록 만든 게 아니라, 납작하게 접히도록 만든 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B0CKVX4RSV",
    image: "https://m.media-amazon.com/images/I/61l31LtKDmL._SL1254_.jpg",
    travel: true,
  },
  {
    category: "playing",
    nameEn: "Pottery Barn Kids Anywhere Chair (Sepia Rose)",
    nameKo: "포터리반 키즈 애니웨어 체어 (세피아 로즈)",
    noteEn: "A small armchair sized for a toddler, sold through a premium home-decor channel rather than a baby-gear aisle — you're paying nursery-interior prices, monogramming included, for something a baby will outgrow in a couple of years. The embroidery is the entire margin.",
    noteKo: "유아 사이즈의 작은 안락의자인데, 육아용품 코너가 아니라 프리미엄 인테리어 채널에서 팔아요 — 이니셜 자수까지 포함해서, 몇 년이면 못 쓰게 될 물건에 인테리어 가격을 내는 셈이에요. 자수가 사실상 마진의 전부예요.",
    amazonUrl: "",
    otherUrl: "https://www.potterybarnkids.com/products/sepia-rose-anywhere-chair-v2/",
  },

  // ================= LITTLE EXTRAS · 소소한 아이템 =================
  {
    category: "extras",
    nameEn: "Fully Lined Baby Hair Clips (20pcs)",
    nameKo: "유아 헤어핀 (20개)",
    noteEn: "A fully lined clip grips fine baby hair without pulling it out — most cheap clips just slide off, so the lining is the entire differentiator worth paying for. Unbranded-feeling, but the one engineering detail that matters is done right.",
    noteKo: "안감 처리된 클립이 아기의 얇은 머리카락을 뽑지 않고 꽉 잡아줘요 — 저가 클립은 대부분 그냥 미끄러져 빠지니, 이 안감이 돈 낼 가치가 있는 유일한 차별점이에요. 브랜드감은 없지만, 정말 중요한 그 한 가지 디테일만큼은 제대로 됐어요.",
    amazonUrl: "https://www.amazon.com/dp/B0CYKNZKNZ",
    image: "https://m.media-amazon.com/images/I/811FRLbaliL._SL1500_.jpg",
  },
  {
    category: "extras",
    nameEn: "Acrylic Magnetic Fridge Dry-Erase Board",
    nameKo: "냉장고 자석 아크릴 메모보드",
    noteEn: "A clear acrylic board for tracking feeds, naps, and who-did-what — the honest product here is the marker set, since any magnetic board would do the same job. Bought for organization, kept for the small daily satisfaction of crossing something off.",
    noteKo: "수유·낮잠·역할 분담을 기록하는 투명 아크릴 보드예요 — 사실 어떤 자석 보드든 같은 역할을 하니, 진짜 제품은 마커 세트예요. 정리하려고 샀지만, 뭔가를 지워나가는 작은 매일의 만족감 때문에 계속 쓰게 돼요.",
    amazonUrl: "https://www.amazon.com/dp/B0BLBZRN9S",
    image: "https://m.media-amazon.com/images/I/71XMNX7uQgL._AC_SL1500_.jpg",
  },
  {
    category: "extras",
    nameEn: "To Have and to Hold — Molly Millwood",
    nameKo: "「To Have and to Hold」 — 몰리 밀우드",
    noteEn: "A psychologist's honest look at how marriages absorb the strain of new parenthood — less parenting advice, more a permission slip to admit the hard parts out loud. Worth reading before the baby arrives, not after, though most people do it backwards.",
    noteKo: "새로운 부모됨이 결혼 생활에 주는 부담을 다룬 심리학자의 솔직한 책이에요 — 육아 조언이라기보다, 힘든 부분을 소리 내어 인정해도 된다는 허락에 가까워요. 아기가 태어나기 전에 읽는 게 좋지만, 대부분 순서를 거꾸로 하죠.",
    amazonUrl: "https://www.amazon.com/dp/0062838652",
    image: "https://m.media-amazon.com/images/I/71cFHwgi9ML._SL1500_.jpg",
  },

  // ---- Added 2026-07-09, round 3 ----
  {
    category: "gear",
    nameEn: "Stonz Cruiser Original Toddler Shoe",
    nameKo: "스톤즈 크루저 오리지널 유아 신발",
    noteEn: "Actual rubber-sole traction on a toddler shoe, which sounds like a low bar until you realize most toddler shoes are just fabric with a logo. A Canadian brand built for real weather, not a runway silhouette shrunk down to kid size.",
    noteKo: "유아 신발에 진짜 고무 밑창 접지력이 있다는 게, 별거 아닌 것 같지만 대부분의 유아 신발이 로고 박힌 천 쪼가리에 불과하다는 걸 알면 생각이 달라져요. 런웨이 디자인을 아이 사이즈로 줄인 게 아니라, 진짜 날씨를 견디도록 만든 캐나다 브랜드예요.",
    amazonUrl: "https://www.amazon.com/dp/B0D9MSRX8B",
    image: "https://m.media-amazon.com/images/I/71MUP8ZWf1L._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Indestructibles: Wheels Go (Amy Pixton)",
    nameKo: "인디스트럭터블스: Wheels Go (에이미 픽스턴)",
    noteEn: "Paper that survives tearing and chewing through actual material engineering, not just a marketing claim on the cover — the publisher's insight was that board books still fail against a determined toddler, and rip-proof fabric-paper doesn't. A quiet pivot from traditional children's-book publishing into a durability-first category.",
    noteKo: "겉표지 마케팅 문구가 아니라 실제 소재 공학으로 찢어지지도 씹혀도 멀쩡해요 — 보드북도 결국 아기 손에 못 버틴다는 걸 파악한 출판사의 인사이트예요. 전통 그림책 출판에서 내구성 우선 카테고리로 조용히 방향을 튼 사례예요.",
    amazonUrl: "https://www.amazon.com/dp/1523517727",
    image: "https://m.media-amazon.com/images/I/81jC4AJ1kqL._SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Bright Starts Around We Go Activity Center",
    nameKo: "브라이트스타츠 어라운드 위 고 액티비티 센터",
    noteEn: "A full 360-degree activity center at a fraction of premium competitors' price — fewer sensors and sounds than pricier options, but a toddler under one rarely notices the difference. The value-pick logic: pay for what a baby actually perceives, not the spec sheet.",
    noteKo: "프리미엄 경쟁 제품 가격의 일부만으로 360도 액티비티 센터를 제공해요 — 센서와 사운드는 더 적지만, 돌 전 아기는 그 차이를 거의 못 느껴요. 스펙시트가 아니라 아기가 실제로 인지하는 것에만 돈을 쓰는 가성비 로직이에요.",
    amazonUrl: "https://www.amazon.com/dp/B08NGBZ753",
    image: "https://m.media-amazon.com/images/I/71yuXW9hQbL._AC_SL1500_.jpg",
    valuePick: true,
  },
  {
    category: "playing",
    nameEn: "VTech Sit-to-Stand Learning Walker (Blue)",
    nameKo: "브이텍 싯투스탠드 학습 워커 (블루)",
    noteEn: "The wheeled base resists tipping better than cheaper walkers, and the button panel actually holds a toddler's attention past the first week — decades of category dominance means this is the walker every other product line still benchmarks against.",
    noteKo: "바퀴 달린 받침대가 저가 워커보다 안 넘어지고, 버튼 패널이 첫 주가 지나도 아이의 관심을 붙잡아둬요 — 수십 년간 이 카테고리를 지배해온 홍콩 브랜드라, 사실상 업계 벤치마크예요.",
    amazonUrl: "https://www.amazon.com/dp/B07CRSXMW8",
    image: "https://m.media-amazon.com/images/I/71wPdebzbEL._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "VTech First Learning Activity Table",
    nameKo: "브이텍 퍼스트 러닝 액티비티 테이블",
    noteEn: "Same button-and-sound playbook as the walker, just in a tabletop format for sitting play instead of standing — same Hong Kong brand betting that a proven mechanism works in a second form factor. It does.",
    noteKo: "워커와 같은 버튼·사운드 전략을 서서 노는 대신 앉아서 노는 테이블 형태로 옮긴 거예요 — 같은 홍콩 브랜드가 검증된 메커니즘을 두 번째 폼팩터에도 적용한 거예요. 실제로 잘 통해요.",
    amazonUrl: "https://www.amazon.com/dp/B07C5HZX1F",
    image: "https://m.media-amazon.com/images/I/71qMAoU3D4L._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "VTech Sit-to-Stand Learning Walker (Lavender)",
    nameKo: "브이텍 싯투스탠드 학습 워커 (라벤더)",
    noteEn: "The lavender SKU of the same Hong Kong-made walker — twin #2 gets her own unit, no negotiating required. Color-coding a duplicate purchase is a small but real parenting-logistics hack, not just a preference.",
    noteKo: "같은 홍콩산 워커의 라벤더 색상이에요. 쌍둥이 2호도 자기 것이 생겨서 협상할 일이 없어요 — 색깔로 구분하는 건 취향이 아니라 작지만 확실한 육아 로지스틱스 팁이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0103AHP90",
    image: "https://m.media-amazon.com/images/I/714OtbajOYS._AC_SL1500_.jpg",
  },
  {
    category: "sleeping",
    nameEn: "BreathableBaby Classic Breathable Mesh Crib Liner",
    nameKo: "브리더블베이비 통기성 메쉬 크립 라이너",
    noteEn: "Breathable mesh that actually addresses the bumper-suffocation-risk concern rather than just slapping a 'breathable' label on regular padded fabric — the material is the entire safety claim, and it holds up. A no-frills answer to a genuinely researched worry.",
    noteKo: "'통기성'이라는 라벨만 붙인 일반 패딩 원단이 아니라, 범퍼 질식 위험 문제를 실제 메쉬 소재로 해결해요 — 소재 자체가 안전성 주장의 전부이고, 실제로 그 역할을 해요. 진지하게 연구된 걱정에 대한 군더더기 없는 답이에요.",
    amazonUrl: "https://www.amazon.com/dp/B0013FGWD0",
    image: "https://m.media-amazon.com/images/I/71eCknpKYsL._SL1500_.jpg",
  },
  {
    category: "gear",
    nameEn: "StoHua Adjustable Neck Support (U-Shaped)",
    nameKo: "스토후아 조절식 목받침 (U자형)",
    noteEn: "A simple foam U cradles a lolling head during car naps — the kind of unbranded-feeling accessory that solves a real problem for a few dollars, no design points needed. You won't remember the brand name, but you'll notice the first nap where their neck doesn't flop.",
    noteKo: "단순한 U자형 폼이 카시트에서 꾸벅거리는 고개를 받쳐줘요 — 브랜드감은 없지만 몇 달러로 진짜 문제를 해결해주는 액세서리예요. 브랜드명은 기억 못 해도, 고개가 안 꺾이는 첫 낮잠은 확실히 알아차릴 거예요.",
    amazonUrl: "https://www.amazon.com/dp/B07W5S9W78",
    image: "https://m.media-amazon.com/images/I/71ax9ayKaVL._SL1200_.jpg",
  },
  {
    category: "sleeping",
    nameEn: "Dofilachy Breathable Blackout Slumber Pod",
    nameKo: "도필라치 통기성 암막 슬럼버 포드",
    noteEn: "A pop-up tent that clips onto a crib or pack-and-play and blocks daylight without blocking airflow — a category-of-one that solves the nap-in-daylight problem most parents just complain about instead of fixing. Bulky to store, the honest cost of actually working.",
    noteKo: "크립이나 플레이야드에 클립으로 고정되는 팝업 텐트가, 통풍은 막지 않으면서 햇빛만 차단해줘요 — 대부분의 부모가 그냥 불평만 하는 낮잠 시간 햇빛 문제를 실제로 해결하는, 경쟁자가 딱히 없는 카테고리예요. 보관할 땐 부피가 큰 게, 실제로 효과가 있는 것에 대한 솔직한 대가예요.",
    amazonUrl: "https://www.amazon.com/dp/B08M16NRZJ",
    image: "https://m.media-amazon.com/images/I/61-RFsB54HL._SL1500_.jpg",
  },

  // ================= FOUND IN ITALY · 이탈리아에서 산 것들 =================
  {
    category: "italy",
    nameEn: "Onligol Kids (Macrogol Constipation Treatment)",
    nameKo: "온리골 키즈 (마크로골 변비약)",
    noteEn: "Tasteless macrogol means no fighting a toddler to take a laxative that tastes like one — the entire product insight is palatability, since the active ingredient is standard. Recommended reflexively by Italian pharmacists, the way ibuprofen is reflexive in the US.",
    noteKo: "무맛 마크로골이라 변비약 특유의 맛과 싸울 필요가 없어요 — 유효 성분은 표준적인데, 맛이 없다는 게 제품의 핵심 인사이트예요. 미국에서 이부프로펜이 반사적으로 나오듯, 이탈리아 약사들이 반사적으로 권해주는 제품이에요.",
    otherUrl: "https://www.amazon.it/dp/B0FDL1F787",
  },
  {
    category: "italy",
    nameEn: "Mustela Mosquito Repellent",
    nameKo: "무스텔라 모기 기피제",
    noteEn: "Safe from 2 months old, which matters enormously in a country where evening mosquitoes are simply part of summer, not an occasional nuisance. Same French pharmacy-brand trust as Mustela's skincare line, extended into a completely different category.",
    noteKo: "생후 2개월부터 사용 가능한데, 저녁 모기가 어쩌다 있는 성가심이 아니라 여름의 기본값인 나라에서는 이게 정말 중요해요. 무스텔라 스킨케어 라인과 같은 프랑스 약국 브랜드 신뢰를, 완전히 다른 제품 카테고리로 확장한 거예요.",
    otherUrl: "https://www.amazon.it/dp/B0C69L8RYB",
  },
  {
    category: "italy",
    nameEn: "Chicco Roll-On Post-Bite Relief",
    nameKo: "치코 벌레물림 진정 롤온",
    noteEn: "A roll-on format for fast, mess-free application on a squirming toddler — Chicco owns this shelf in every Italian farmacia the way Neutrogena owns a US drugstore aisle. Local category dominance you simply don't see once you're back on Amazon.com.",
    noteKo: "꿈틀대는 아이에게 빠르고 깔끔하게 바를 수 있는 롤온 포맷이에요 — 미국 드럭스토어에서 뉴트로지나가 차지하는 자리를, 이탈리아 약국에서는 치코가 차지하고 있어요. 미국 아마존으로 돌아오면 절대 볼 수 없는 현지 카테고리 장악력이에요.",
    otherUrl: "https://www.amazon.it/dp/B07BYR8TWH",
  },
  {
    category: "italy",
    nameEn: "Fisher-Price Laugh & Learn Musical Plush (Multilingual)",
    nameKo: "피셔프라이스 뮤지컬 플러시 토이 (다국어)",
    noteEn: "Identical toy to the one sold in the US, just re-recorded in Italian, Spanish, and Portuguese — a low-cost localization strategy (same mold, new audio chip) rather than a genuinely different product. A nice souvenir precisely because the underlying toy is already proven.",
    noteKo: "미국에서 파는 것과 똑같은 장난감인데, 이탈리아어·스페인어·포르투갈어로 다시 녹음됐을 뿐이에요 — 완전히 다른 제품이 아니라, 같은 금형에 오디오 칩만 바꾼 저비용 현지화 전략이에요. 이미 검증된 장난감이라서 기념품으로도 딱 좋아요.",
    otherUrl: "https://www.amazon.it/dp/B0D7ZV3H7L",
  },
  {
    category: "italy",
    nameEn: "Chicco NaturalZ Protective Gel",
    nameKo: "치코 내추럴Z 방충 젤",
    noteEn: "Citronella and eucalyptus for the parts of an Italian summer no guidebook mentions — mosquitoes that don't care about your vacation itinerary. Chicco's answer to a problem more acute in Italy than in most markets its parent company Artsana serves.",
    noteKo: "가이드북엔 안 나오지만 여행 일정 따위 신경 안 쓰는 모기들을 위한, 시트로넬라·유칼립투스 젤이에요. 치코의 모회사 Artsana가 진출한 대부분의 시장보다 이탈리아에서 훨씬 절실한 문제에 대한 답이에요.",
    otherUrl: "https://www.amazon.it/dp/B0BW15CTCK",
  },
  {
    category: "italy",
    nameEn: "HiPP Organic Lip Balm",
    nameKo: "HiPP 유기농 립밤",
    noteEn: "German organic-baby-care credibility (the same company behind HiPP formula) applied to something as small as a lip balm — you're buying the parent brand's reputation more than evaluating this one product on its own. Found in every Italian farmacia despite being a German import.",
    noteKo: "HiPP 분유로 유명한 그 회사의 독일산 유기농 육아 신뢰도가, 립밤처럼 작은 제품에도 그대로 적용돼요 — 이 제품 하나를 평가한다기보다 모브랜드의 명성을 사는 셈이에요. 독일 수입품인데도 이탈리아 약국이면 어디서나 있어요.",
    otherUrl: "https://www.amazon.it/dp/B0CWP9Z56F",
  },
  {
    category: "italy",
    nameEn: "Mentadent Kids Toothpaste",
    nameKo: "멘타덴트 키즈 치약",
    noteEn: "A cartoon character on the tube does the actual persuading, since no toddler independently prefers 97%-natural-origin ingredients — Mentadent's Italian market share owes more to the mascot than the formulation. Works exactly as well as it needs to for a toddler who mostly just wants to see the character.",
    noteKo: "97% 천연 유래 성분을 굳이 선호하는 유아는 없으니, 튜브에 그려진 캐릭터가 실제 설득을 담당해요 — 멘타덴트의 이탈리아 시장 점유율은 포뮬레이션보다 마스코트 덕이 커요. 캐릭터를 보고 싶어하는 아이에게는, 딱 필요한 만큼 효과가 있어요.",
    otherUrl: "https://www.amazon.it/dp/B0DYK9QNJH",
  },
  {
    category: "italy",
    nameEn: "Chicco Portable Ultrasonic Mosquito Repellent",
    nameKo: "치코 휴대용 초음파 모기 퇴치기",
    noteEn: "Battery-powered and chemical-free — a clip-on that appeals to parents wary of spraying repellent directly near a stroller. Whether ultrasonic repellents actually work is genuinely disputed in entomology research; you're buying the reassurance of 'doing something' as much as proven efficacy.",
    noteKo: "배터리로 작동하고 화학 성분이 없어요 — 유모차 근처에 직접 스프레이 뿌리는 걸 꺼리는 부모를 위한 클립형 제품이에요. 초음파 퇴치기의 실제 효과는 곤충학 연구에서도 의견이 갈리는 부분이라, 검증된 효능만큼이나 '뭔가 하고 있다'는 안심을 사는 셈이에요.",
    otherUrl: "https://www.amazon.it/dp/B00T69BPVY",
  },

  // ---- Added 2026-07-13 ----
  {
    category: "feeding",
    nameEn: "Doddl Toddler Spoon & Fork Set",
    nameKo: "도들 유아 스푼 포크 세트",
    noteEn: "The double-sided handle stays balanced no matter how a toddler grips it, so food actually makes it to the mouth instead of the bib — ergonomics are the entire pitch, not the color options. A UK brand solving self-feeding through geometry rather than gimmicks.",
    noteKo: "양쪽에 손잡이가 있는 디자인 덕분에 아이가 어떻게 쥐어도 균형이 잡혀서, 음식이 턱받이가 아니라 입으로 들어가요 — 색상 옵션보다 인체공학이 이 제품의 전부예요. 영국 브랜드가 잔재주가 아니라 기하학으로 자기주도 식사 문제를 푼 사례예요.",
    amazonUrl: "https://www.amazon.com/dp/B0779CZ9FD",
    image: "https://m.media-amazon.com/images/I/61QPedkOCML._AC_SL1500_.jpg",
  },
  {
    category: "playing",
    nameEn: "Fisher-Price Jumperoo",
    nameKo: "피셔프라이스 점퍼루",
    noteEn: "A rotating seat and a ring of noisy, lightable toys turn bouncing into a genuinely absorbing activity, buying a solid twenty minutes of hands-free time. The height-adjustable frame lasts through an actual growth spurt, not just one size window — rare restraint in a toy category built on obsolescence.",
    noteKo: "회전하는 시트와 소리 나고 불이 켜지는 장난감 링이 통통 튀는 걸 진짜 몰입되는 놀이로 만들어줘서, 손이 자유로운 20분을 확실히 벌어줘요. 높이 조절 프레임이라 한 사이즈만 맞으면 끝나는 게 아니라 성장기 내내 쓸 수 있어요 — 금방 못 쓰게 만드는 장난감 카테고리치고는 드문 절제예요.",
    amazonUrl: "https://www.amazon.com/dp/B0D2CK1DV1",
    image: "https://m.media-amazon.com/images/I/51oBhthSGrL._SL1001_.jpg",
  },
  {
    category: "playing",
    nameEn: "Moover Wooden Ride-On Bike",
    nameKo: "무버 원목 라이드온 바이크",
    noteEn: "Solid wood and silent wheels mean no plastic rattle rolling across hardwood floors at 6am — a Danish design brand charging a real premium for materials most competitors skip entirely. Not sold on Amazon; ordered directly from the brand, closer to buying furniture than a toy.",
    noteKo: "원목과 소음 없는 바퀴 덕분에 새벽 6시에 플라스틱 덜컹거리는 소리 없이 마룻바닥을 굴러다녀요 — 대부분의 경쟁 제품이 아예 생략하는 소재에 제대로 프리미엄을 매기는 덴마크 디자인 브랜드예요. 아마존엔 없고 브랜드 직구인데, 장난감이라기보다 가구를 사는 느낌에 가까워요.",
    otherUrl: "https://www.moovershop.com/products/ride-on-bike-4-wheels-red",
  },
  {
    category: "playing",
    nameEn: "IKEA DVÄRGMÅS Children's Tent",
    nameKo: "이케아 드베리모스 어린이 텐트",
    noteEn: "Connects directly to the matching tunnel to form one long crawl-through play set, rather than being a standalone hideout — the modularity is the actual design idea, not the tent shape itself. Same IKEA formula as always: good enough, cheap enough, no design brief required.",
    noteKo: "짝을 이루는 터널과 직접 연결돼서 하나의 긴 놀이 코스가 되는, 독립된 아지트가 아니라 모듈형 구조가 핵심 아이디어예요. 늘 그렇듯 이케아 공식이에요 — 적당히 좋고, 충분히 저렴하고, 디자인 기획서가 필요 없어요.",
    otherUrl: "https://www.ikea.com/us/en/p/dvaergmas-childrens-tent-green-70547600/",
  },
  {
    category: "playing",
    nameEn: "IKEA DVÄRGMÅS Play Tunnel",
    nameKo: "이케아 드베리모스 플레이 터널",
    noteEn: "Presses flat for storage and clips onto the matching tent to extend the crawl path — the entire product is a fabric hoop, priced and built exactly like one. Multiple tunnels connect end to end if a toddler's ambitions outgrow the living room.",
    noteKo: "보관할 땐 납작하게 눌러지고, 짝꿍 텐트에 연결하면 기어다니는 코스가 길어져요 — 사실 원단 후프 하나가 제품의 전부고, 가격도 딱 그만큼이에요. 아이의 야망이 거실을 넘어서면 터널 여러 개를 이어 붙일 수도 있어요.",
    otherUrl: "https://www.ikea.com/us/en/p/dvaergmas-play-tunnel-blue-green-90547595/",
  },
];
